package com.cnone.khaled;


import com.codename1.components.ImageViewer;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import java.util.ArrayList;
import java.util.List;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    //var
    List<Contact> contacts;
    private Form current;
    private Resources theme;

    public void init(Object context) {
        
        
        
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        
        //Charge contacts list
        contacts = new ArrayList<>();
            //1
            contacts.add(new Contact("Khaled Guedria", "khaled.guedria@esprit.tn", "1.png"));
            //2
            contacts.add(new Contact("Mohamed Salah", "mohamed.salah@esprit.tn", "2.png"));
            //3
            contacts.add(new Contact("Maria Sharapova", "maria.sharapova@esprit.tn", "3.png"));

    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form f = new Form("Contacts", BoxLayout.y());
        for (Contact c : contacts) {
           CustomCell mCell = new CustomCell(theme, c);
           f.addAll(mCell, new Label(" ", "Separator"));
           
           //on Cell Click 
           mCell.addPointerPressedListener((evt) -> {
               
               //Form 2
               Form f2 = new Form(c.getName(), BoxLayout.xCenter());
               
               f2.getToolbar().addMaterialCommandToLeftBar("", FontImage.MATERIAL_ARROW_BACK, (ev) -> {
                   f.showBack();
               });
               
               Container ctn = new Container(BoxLayout.y());
               ctn.addAll(new ImageViewer(theme.getImage(c.getImage())), new Label(c.getEmail()));
               f2.add(ctn);
               f2.show();
               
           });
           }
        
        f.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
